version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: meilisearch-ebook-reader
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=development  # Use 'production' for production
      # - MEILI_MASTER_KEY=your-master-key-here  # Uncomment and change this for production
    volumes:
      - meilisearch_data:/meili_data
    restart: unless-stopped

volumes:
  meilisearch_data:
    driver: local